name: Pull Request Testing

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Docker environment
      run: docker-compose up -d

    - name: Build the Docker image
      run: docker-compose build flask_app test

    - name: Run tests
      run: docker-compose run test

    - name: Clean up
      if: always()
      run: docker-compose down
